<a href="https://colab.research.google.com/github/Hira63S/DS-Unit-1-Sprint-4-Statistical-Tests-and-Experiments/blob/master/Hira_LS_DS3_142_Sampling_Confidence_Intervals_and_Hypothesis_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lambda School Data Science Module 142
## Sampling, Confidence Intervals, and Hypothesis Testing

## Prepare - examine other available hypothesis tests

If you had to pick a single hypothesis test in your toolbox, t-test would probably be the best choice - but the good news is you don't have to pick just one! Here's some of the others to be aware of:

In [1]:
import numpy as np
from scipy.stats import chisquare  # One-way chi square test

# Chi square can take any crosstab/table and test the independence of rows/cols
# The null hypothesis is that the rows/cols are independent -> low chi square
# The alternative is that there is a dependence -> high chi square
# Be aware! Chi square does *not* tell you direction/causation

ind_obs = np.array([[1, 1], [2, 2]]).T
print(ind_obs)
print(chisquare(ind_obs, axis=None))

dep_obs = np.array([[16, 18, 16, 14, 12, 12], [32, 24, 16, 28, 20, 24]]).T
print(dep_obs)
print(chisquare(dep_obs, axis=None))

[[1 2]
 [1 2]]
Power_divergenceResult(statistic=0.6666666666666666, pvalue=0.8810148425137847)
[[16 32]
 [18 24]
 [16 16]
 [14 28]
 [12 20]
 [12 24]]
Power_divergenceResult(statistic=23.31034482758621, pvalue=0.015975692534127565)


In [4]:
# Distribution tests:
# We often assume that something is normal, but it can be important to *check*

# For example, later on with predictive modeling, a typical assumption is that
# residuals (prediction errors) are normal - checking is a good diagnostic

from scipy.stats import normaltest
# Poisson models arrival times and is related to the binomial (coinflip)
sample = np.random.poisson(5, 1000)
print(normaltest(sample))  # Pretty clearly not normal

NormaltestResult(statistic=36.238585852367706, pvalue=1.351733466155494e-08)


In [5]:
# Kruskal-Wallis H-test - compare the median rank between 2+ groups
# Can be applied to ranking decisions/outcomes/recommendations
# The underlying math comes from chi-square distribution, and is best for n>5
from scipy.stats import kruskal

x1 = [1, 3, 5, 7, 9]
y1 = [2, 4, 6, 8, 10]
print(kruskal(x1, y1))  # x1 is a little better, but not "significantly" so

x2 = [1, 1, 1]
y2 = [2, 2, 2]
z = [2, 2]  # Hey, a third group, and of different size!
print(kruskal(x2, y2, z))  # x clearly dominates

KruskalResult(statistic=0.2727272727272734, pvalue=0.6015081344405895)
KruskalResult(statistic=7.0, pvalue=0.0301973834223185)


In [31]:
import pandas as pd

gender = ['male', 'male', 'male', 'female', 'female', 'female']
eat_outside = ['outside', 'inside', 'inside', 'inside', 'outside', 'outside']

df = pd.DataFrame({"gender": gender, "preference":eat_outside})
df.head()

gender preference
0    male    outside
1    male     inside
2    male     inside
3  female     inside
4  female    outside

In [0]:
df = df['preference'].map({'outside':1, 'inside':0})

In [0]:
df.head()

In [0]:
table = pd.crosstab(df.gender, df.preference)

In [23]:
pd.crosstab(df.gender, df.preference, margins = True)

preference  inside  outside  All
gender                          
female           1        2    3
male             2        1    3
All              3        3    6

In [33]:
df = df.replace("male", 0)
df = df.replace('female', 1)
df = df.replace("outside", 0)
df = df.replace('inside', 1)

df.head(6)

gender  preference
0       0           0
1       0           1
2       0           1
3       1           1
4       1           0
5       1           0

In [35]:
pd.crosstab(df.gender, df.preference, margins = True)

preference  0  1  All
gender               
0           1  2    3
1           2  1    3
All         3  3    6

In [0]:
expected = np.array([[6/4, 6/4],
                    [6/4, 6/4]])

In [0]:
observed = np.array([[3/6, 3/6],
           [3/6, 3/6]])

In [46]:
numerator = observed - expected
print(numerator)

[[-1. -1.]
 [-1. -1.]]


In [0]:
deviation = numerator

deviation_squared = deviation**2

In [49]:
print("deviation squared \n", deviation_squared)

deviation squared 
 [[1. 1.]
 [1. 1.]]


In [50]:
fraction = (deviation_squared/expected)

fraction

array([[0.66666667, 0.66666667],
       [0.66666667, 0.66666667]])

In [51]:
chi2 = fraction.sum()
print(chi2/4)

0.6666666666666666


In [39]:
pd.crosstab(df.gender, df.preference, margins = True, normalize= 'all')

preference         0         1  All
gender                             
0           0.166667  0.333333  0.5
1           0.333333  0.166667  0.5
All         0.500000  0.500000  1.0

In [54]:
from scipy.stats import chisquare

chi_data = [[1,2],
           [2,1]]


chisquare(chi_data, axis = None)



Power_divergenceResult(statistic=0.6666666666666666, pvalue=0.8810148425137847)

In [0]:
from scipy.stats import chi2_contingency

table = [[1,2],
        [2, 4]]

chi2statistic, pvalue, dof, observed = chi2_contingency(table)

#Confidence Intervals #

In [0]:
# confidence_interval = [lower_bound, upper_bound]



In [7]:
coinflips = np.random.binomial(n=1, p=0.5, size = 100)

print(coinflips)

[0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 0 0 1 1 0 0 0 1 1 0 0 1 0
 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1
 0 1 0 1 0 1 0 0 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1]


In [8]:
import scipy.stats as stats


stats.ttest_1samp(coinflips, 0.5)

Ttest_1sampResult(statistic=-0.39831375340784614, pvalue=0.6912566363051549)

In [0]:
import numpy as np
from scipy import stats

def confidence_interval(data, confidence= 0.95):
  data = np.array(data)
  mean = np.mean(data)
  n = len(data)
  stderr = stats.sem(data)
  interval = stderr * stats.t.ppf((1+confidence) /2.,n-1)
  return(mean, mean - interval, mean + interval)
                 

In [0]:
def report_confidence_interval(confidence_interval):
  
  s = 'our mean lies in the interval [{:.2}, {:.2}]'.format(
    confidence_interval[1], confidence_interval[2])
  return s

In [60]:
coinflip_interval = confidence_interval(coinflips)
coinflip_interval

(0.48, 0.38036914695852936, 0.5796308530414707)

And there's many more! `scipy.stats` is fairly comprehensive, though there are even more available if you delve into the extended world of statistics packages. As tests get increasingly obscure and specialized, the importance of knowing them by heart becomes small - but being able to look them up and figure them out when they *are* relevant is still important.

## Live Lecture - let's explore some more of scipy.stats

Candidate topics to explore:

- `scipy.stats.chi2` - the Chi-squared distribution, which we can use to reproduce the Chi-squared test
- Calculate the Chi-Squared test statistic "by hand" (with code), and feed it into `chi2`
- Build a confidence interval with `stats.t.ppf`, the t-distribution percentile point function (the inverse of the CDF) - we can write a function to return a tuple of `(mean, lower bound, upper bound)` that you can then use for the assignment (visualizing confidence intervals)

In [0]:
# Taking requests! Come to lecture with a topic or problem and we'll try it.

## Assignment - Build a confidence interval

A confidence interval refers to a neighborhood around some point estimate, the size of which is determined by the desired p-value. For instance, we might say that 52% of Americans prefer tacos to burritos, with a 95% confidence interval of +/- 5%.

52% (0.52) is the point estimate, and +/- 5% (the interval $[0.47, 0.57]$) is the confidence interval. "95% confidence" means a p-value $\leq 1 - 0.95 = 0.05$.

In this case, the confidence interval includes $0.5$ - which is the natural null hypothesis (that half of Americans prefer tacos and half burritos, thus there is no clear favorite). So in this case, we could use the confidence interval to report that we've failed to reject the null hypothesis.

But providing the full analysis with a confidence interval, including a graphical representation of it, can be a helpful and powerful way to tell your story. Done well, it is also more intuitive to a layperson than simply saying "fail to reject the null hypothesis" - it shows that in fact the data does *not* give a single clear result (the point estimate) but a whole range of possibilities.

How is a confidence interval built, and how should it be interpreted? It does *not* mean that 95% of the data lies in that interval - instead, the frequentist interpretation is "if we were to repeat this experiment 100 times, we would expect the average result to lie in this interval ~95 times."

For a 95% confidence interval and a normal(-ish) distribution, you can simply remember that +/-2 standard deviations contains 95% of the probability mass, and so the 95% confidence interval based on a given sample is centered at the mean (point estimate) and has a range of +/- 2 (or technically 1.96) standard deviations.

Different distributions/assumptions (90% confidence, 99% confidence) will require different math, but the overall process and interpretation (with a frequentist approach) will be the same.

Your assignment - using the data from the prior module ([congressional voting records](https://archive.ics.uci.edu/ml/datasets/Congressional+Voting+Records)):

1. Generate and numerically represent a confidence interval
2. Graphically (with a plot) represent the confidence interval
3. Interpret the confidence interval - what does it tell you about the data and its distribution?

Stretch goals:

1. Write a summary of your findings, mixing prose and math/code/results. *Note* - yes, this is by definition a political topic. It is challenging but important to keep your writing voice *neutral* and stick to the facts of the data. Data science often involves considering controversial issues, so it's important to be sensitive about them (especially if you want to publish).
2. Apply the techniques you learned today to your project data or other data of your choice, and write/discuss your findings here.
3. Refactor your code so it is elegant, readable, and can be easily run for all issues.

In [0]:
# TODO - your code!

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy

column_names = ['Party', 'handicapped-infants', 'water-project-cost-sharing', 'adoption-of-the-budget-resolution',
           'physician-fee-freeze', 'el-salvador-aid', 'religious-groups-in-schools', 'anti-satellite-test-ban',
           'aid-to-nicaraguan-contras', 'mx-missile', 'immigration', 'synfuels-corporation-cutback', 'education-spending',
           'superfund-right-to-sue', 'crime', 'duty-free-exports', 'export-administration-act-south-africa']


url = 'https://raw.githubusercontent.com/Hira63S/Congress-data/master/house-votes-84%20(1).data'

df = pd.read_csv(url, header = None, names=column_names)




In [0]:
df = df.replace({'?': np.nan})

In [95]:
df.head()

Party  handicapped-infants  water-project-cost-sharing  \
5     democrat                    0                           1   
8   republican                    0                           1   
19    democrat                    1                           1   
23    democrat                    1                           1   
25    democrat                    1                           0   

    adoption-of-the-budget-resolution  physician-fee-freeze  el-salvador-aid  \
5                                   1                     0                1   
8                                   0                     1                1   
19                                  1                     0                0   
23                                  1                     0                0   
25                                  1                     0                0   

    religious-groups-in-schools  anti-satellite-test-ban  \
5                             1                        0   
8                             1                        0   
19                            0                        1   
23                            0                        1   
25                            0                        1   

    aid-to-nicaraguan-contras  mx-missile  immigration  \
5                           0           0            0   
8                           0           0            0   
19                          1           1            0   
23                          1           1            0   
25                          1           1            1   

    synfuels-corporation-cutback  education-spending  superfund-right-to-sue  \
5                              0                   0                       1   
8                              0                   1                       1   
19                             1                   0                       0   
23                             0                   0                       0   
25                             0                   0                       0   

    crime  duty-free-exports  export-administration-act-south-africa  
5       1                  1                                       1  
8       1                  0                                       1  
19      0                  1                                       1  
23      0                  1                                       1  
25      0                  1                                       1

In [101]:
df = df.replace({'n':-1,'?':0,'y':1})

df.head()

Party  handicapped-infants  water-project-cost-sharing  \
0  republican                   -1                           1   
1  republican                   -1                           1   
2    democrat                    0                           1   
3    democrat                   -1                           1   
4    democrat                    1                           1   

   adoption-of-the-budget-resolution  physician-fee-freeze  el-salvador-aid  \
0                                 -1                     1                1   
1                                 -1                     1                1   
2                                  1                     0                1   
3                                  1                    -1                0   
4                                  1                    -1                1   

   religious-groups-in-schools  anti-satellite-test-ban  \
0                            1                       -1   
1                            1                       -1   
2                            1                       -1   
3                            1                       -1   
4                            1                       -1   

   aid-to-nicaraguan-contras  mx-missile  immigration  \
0                         -1          -1            1   
1                         -1          -1           -1   
2                         -1          -1           -1   
3                         -1          -1           -1   
4                         -1          -1           -1   

   synfuels-corporation-cutback  education-spending  superfund-right-to-sue  \
0                             0                   1                       1   
1                            -1                   1                       1   
2                             1                  -1                       1   
3                             1                  -1                       1   
4                             1                   0                       1   

   crime  duty-free-exports  export-administration-act-south-africa  
0      1                 -1                                       1  
1      1                 -1                                       0  
2      1                 -1                                      -1  
3     -1                 -1                                       1  
4      1                  1                                       1

In [0]:
democrats = df[df['Party'] == 'democrat']

republicans = df[df['Party'] == 'republican']

In [103]:
interval = confidence_interval(df['physician-fee-freeze'])

interval

(-0.16091954022988506, -0.25281782339179204, -0.06902125706797808)

In [105]:
dem_mean = democrats['physician-fee-freeze'].mean()
rep_mean = republicans['physician-fee-freeze'].mean()

mean = dem_mean - rep_mean

mean

-1.823501872659176

In [106]:
dem_mean

-0.8651685393258427

In [107]:
rep_mean

0.9583333333333334

In [0]:
interval = confidence_interval(df['physician-fee-freeze'])

In [109]:
interval

(-0.16091954022988506, -0.25281782339179204, -0.06902125706797808)

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)