<a href="https://colab.research.google.com/github/ty3117/DS-Unit-1-Sprint-3-Statistical-Tests-and-Experiments/blob/master/Tyler_Sheppard_DS_Unit_1_Sprint_Challenge_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science Unit 1 Sprint Challenge 3

## Exploring Data, Testing Hypotheses

In this sprint challenge you will look at a dataset of people being approved or rejected for credit.

https://archive.ics.uci.edu/ml/datasets/Credit+Approval

Data Set Information: This file concerns credit card applications. All attribute names and values have been changed to meaningless symbols to protect confidentiality of the data. This dataset is interesting because there is a good mix of attributes -- continuous, nominal with small numbers of values, and nominal with larger numbers of values. There are also a few missing values.

Attribute Information:
- A1: b, a.
- A2: continuous.
- A3: continuous.
- A4: u, y, l, t.
- A5: g, p, gg.
- A6: c, d, cc, i, j, k, m, r, q, w, x, e, aa, ff.
- A7: v, h, bb, j, n, z, dd, ff, o.
- A8: continuous.
- A9: t, f.
- A10: t, f.
- A11: continuous.
- A12: t, f.
- A13: g, p, s.
- A14: continuous.
- A15: continuous.
- A16: +,- (class attribute)

Yes, most of that doesn't mean anything. A16 (the class attribute) is the most interesting, as it separates the 307 approved cases from the 383 rejected cases. The remaining variables have been obfuscated for privacy - a challenge you may have to deal with in your data science career.

Sprint challenges are evaluated based on satisfactory completion of each part. It is suggested you work through it in order, getting each aspect reasonably working, before trying to deeply explore, iterate, or refine any given step. Once you get to the end, if you want to go back and improve things, go for it!

## Part 1 - Load and validate the data

- Load the data as a `pandas` data frame.
- Validate that it has the appropriate number of observations (you can check the raw file, and also read the dataset description from UCI).
- UCI says there should be missing data - check, and if necessary change the data so pandas recognizes it as na
- Make sure that the loaded features are of the types described above (continuous values should be treated as float), and correct as necessary

This is review, but skills that you'll use at the start of any data exploration. Further, you may have to do some investigation to figure out which file to load from - that is part of the puzzle.

In [1]:
import pandas as pd

column_headers = ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16']
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data', header=None, names=column_headers)
df.head(100)


A1     A2      A3 A4 A5  A6  A7  ...  A10 A11 A12  A13    A14    A15 A16
0   b  30.83   0.000  u  g   w   v  ...    t   1   f    g  00202      0   +
1   a  58.67   4.460  u  g   q   h  ...    t   6   f    g  00043    560   +
2   a  24.50   0.500  u  g   q   h  ...    f   0   f    g  00280    824   +
3   b  27.83   1.540  u  g   w   v  ...    t   5   t    g  00100      3   +
4   b  20.17   5.625  u  g   w   v  ...    f   0   f    s  00120      0   +
5   b  32.08   4.000  u  g   m   v  ...    f   0   t    g  00360      0   +
6   b  33.17   1.040  u  g   r   h  ...    f   0   t    g  00164  31285   +
7   a  22.92  11.585  u  g  cc   v  ...    f   0   f    g  00080   1349   +
8   b  54.42   0.500  y  p   k   h  ...    f   0   f    g  00180    314   +
9   b  42.50   4.915  y  p   w   v  ...    f   0   t    g  00052   1442   +
10  b  22.08   0.830  u  g   c   h  ...    f   0   t    g  00128      0   +
11  b  29.92   1.835  u  g   c   h  ...    f   0   f    g  00260    200   +
12  a  38.25   6.000  u  g   k   v  ...    f   0   t    g  00000      0   +
13  b  48.08   6.040  u  g   k   v  ...    f   0   f    g  00000   2690   +
14  a  45.83  10.500  u  g   q   v  ...    t   7   t    g  00000      0   +
15  b  36.67   4.415  y  p   k   v  ...    t  10   t    g  00320      0   +
16  b  28.25   0.875  u  g   m   v  ...    t   3   t    g  00396      0   +
17  a  23.25   5.875  u  g   q   v  ...    t  10   f    g  00120    245   +
18  b  21.83   0.250  u  g   d   h  ...    f   0   t    g  00000      0   +
19  a  19.17   8.585  u  g  cc   h  ...    t   7   f    g  00096      0   +
20  b  25.00  11.250  u  g   c   v  ...    t  17   f    g  00200   1208   +
21  b  23.25   1.000  u  g   c   v  ...    f   0   f    s  00300      0   +
22  a  47.75   8.000  u  g   c   v  ...    t   6   t    g  00000   1260   +
23  a  27.42  14.500  u  g   x   h  ...    t   1   f    g  00120     11   +
24  a  41.17   6.500  u  g   q   v  ...    t   3   t    g  00145      0   +
25  a  15.83   0.585  u  g   c   h  ...    t   2   f    g  00100      0   +
26  a  47.00  13.000  u  g   i  bb  ...    t   9   t    g  00000      0   +
27  b  56.58  18.500  u  g   d  bb  ...    t  17   t    g  00000      0   +
28  b  57.42   8.500  u  g   e   h  ...    t   3   f    g  00000      0   +
29  b  42.08   1.040  u  g   w   v  ...    t   6   t    g  00500  10000   +
.. ..    ...     ... .. ..  ..  ..  ...  ...  ..  ..  ...    ...    ...  ..
70  b  32.33   7.500  u  g   e  bb  ...    f   0   t    s  00420      0   -
71  b  34.83   4.000  u  g   d  bb  ...    f   0   t    g      ?      0   -
72  a  38.58   5.000  u  g  cc   v  ...    f   0   t    g  00980      0   -
73  b  44.25   0.500  u  g   m   v  ...    f   0   f    s  00400      0   -
74  b  44.83   7.000  y  p   c   v  ...    f   0   f    g  00160      2   -
75  b  20.67   5.290  u  g   q   v  ...    t   1   f    g  00160      0   -
76  b  34.08   6.500  u  g  aa   v  ...    f   0   t    g  00443      0   -
77  a  19.17   0.585  y  p  aa   v  ...    f   0   t    g  00160      0   -
78  b  21.67   1.165  y  p   k   v  ...    t   1   f    g  00180     20   -
79  b  21.50   9.750  u  g   c   v  ...    f   0   f    g  00140      0   -
80  b  49.58  19.000  u  g  ff  ff  ...    t   1   f    g  00094      0   -
81  a  27.67   1.500  u  g   m   v  ...    f   0   f    s  00368      0   -
82  b  39.83   0.500  u  g   m   v  ...    f   0   f    s  00288      0   -
83  a      ?   3.500  u  g   d   v  ...    f   0   t    g  00300      0   -
84  b  27.25   0.625  u  g  aa   v  ...    f   0   t    g  00200      0   -
85  b  37.17   4.000  u  g   c  bb  ...    f   0   t    s  00280      0   -
86  b      ?   0.375  u  g   d   v  ...    f   0   t    s  00928      0   -
87  b  25.67   2.210  y  p  aa   v  ...    f   0   f    g  00188      0   -
88  b  34.00   4.500  u  g  aa   v  ...    f   0   t    g  00240      0   -
89  a  49.00   1.500  u  g   j   j  ...    f   0   t    g  00100     27   -
90  b  62.50  12.750  y  p   c   h  ...    f   0   

In [2]:
import numpy as np

df = df.replace({'?':np.NaN})
df.head(100)

A1     A2      A3 A4 A5  A6  A7  ...  A10 A11 A12  A13    A14    A15 A16
0   b  30.83   0.000  u  g   w   v  ...    t   1   f    g  00202      0   +
1   a  58.67   4.460  u  g   q   h  ...    t   6   f    g  00043    560   +
2   a  24.50   0.500  u  g   q   h  ...    f   0   f    g  00280    824   +
3   b  27.83   1.540  u  g   w   v  ...    t   5   t    g  00100      3   +
4   b  20.17   5.625  u  g   w   v  ...    f   0   f    s  00120      0   +
5   b  32.08   4.000  u  g   m   v  ...    f   0   t    g  00360      0   +
6   b  33.17   1.040  u  g   r   h  ...    f   0   t    g  00164  31285   +
7   a  22.92  11.585  u  g  cc   v  ...    f   0   f    g  00080   1349   +
8   b  54.42   0.500  y  p   k   h  ...    f   0   f    g  00180    314   +
9   b  42.50   4.915  y  p   w   v  ...    f   0   t    g  00052   1442   +
10  b  22.08   0.830  u  g   c   h  ...    f   0   t    g  00128      0   +
11  b  29.92   1.835  u  g   c   h  ...    f   0   f    g  00260    200   +
12  a  38.25   6.000  u  g   k   v  ...    f   0   t    g  00000      0   +
13  b  48.08   6.040  u  g   k   v  ...    f   0   f    g  00000   2690   +
14  a  45.83  10.500  u  g   q   v  ...    t   7   t    g  00000      0   +
15  b  36.67   4.415  y  p   k   v  ...    t  10   t    g  00320      0   +
16  b  28.25   0.875  u  g   m   v  ...    t   3   t    g  00396      0   +
17  a  23.25   5.875  u  g   q   v  ...    t  10   f    g  00120    245   +
18  b  21.83   0.250  u  g   d   h  ...    f   0   t    g  00000      0   +
19  a  19.17   8.585  u  g  cc   h  ...    t   7   f    g  00096      0   +
20  b  25.00  11.250  u  g   c   v  ...    t  17   f    g  00200   1208   +
21  b  23.25   1.000  u  g   c   v  ...    f   0   f    s  00300      0   +
22  a  47.75   8.000  u  g   c   v  ...    t   6   t    g  00000   1260   +
23  a  27.42  14.500  u  g   x   h  ...    t   1   f    g  00120     11   +
24  a  41.17   6.500  u  g   q   v  ...    t   3   t    g  00145      0   +
25  a  15.83   0.585  u  g   c   h  ...    t   2   f    g  00100      0   +
26  a  47.00  13.000  u  g   i  bb  ...    t   9   t    g  00000      0   +
27  b  56.58  18.500  u  g   d  bb  ...    t  17   t    g  00000      0   +
28  b  57.42   8.500  u  g   e   h  ...    t   3   f    g  00000      0   +
29  b  42.08   1.040  u  g   w   v  ...    t   6   t    g  00500  10000   +
.. ..    ...     ... .. ..  ..  ..  ...  ...  ..  ..  ...    ...    ...  ..
70  b  32.33   7.500  u  g   e  bb  ...    f   0   t    s  00420      0   -
71  b  34.83   4.000  u  g   d  bb  ...    f   0   t    g    NaN      0   -
72  a  38.58   5.000  u  g  cc   v  ...    f   0   t    g  00980      0   -
73  b  44.25   0.500  u  g   m   v  ...    f   0   f    s  00400      0   -
74  b  44.83   7.000  y  p   c   v  ...    f   0   f    g  00160      2   -
75  b  20.67   5.290  u  g   q   v  ...    t   1   f    g  00160      0   -
76  b  34.08   6.500  u  g  aa   v  ...    f   0   t    g  00443      0   -
77  a  19.17   0.585  y  p  aa   v  ...    f   0   t    g  00160      0   -
78  b  21.67   1.165  y  p   k   v  ...    t   1   f    g  00180     20   -
79  b  21.50   9.750  u  g   c   v  ...    f   0   f    g  00140      0   -
80  b  49.58  19.000  u  g  ff  ff  ...    t   1   f    g  00094      0   -
81  a  27.67   1.500  u  g   m   v  ...    f   0   f    s  00368      0   -
82  b  39.83   0.500  u  g   m   v  ...    f   0   f    s  00288      0   -
83  a    NaN   3.500  u  g   d   v  ...    f   0   t    g  00300      0   -
84  b  27.25   0.625  u  g  aa   v  ...    f   0   t    g  00200      0   -
85  b  37.17   4.000  u  g   c  bb  ...    f   0   t    s  00280      0   -
86  b    NaN   0.375  u  g   d   v  ...    f   0   t    s  00928      0   -
87  b  25.67   2.210  y  p  aa   v  ...    f   0   f    g  00188      0   -
88  b  34.00   4.500  u  g  aa   v  ...    f   0   t    g  00240      0   -
89  a  49.00   1.500  u  g   j   j  ...    f   0   t    g  00100     27   -
90  b  62.50  12.750  y  p   c   h  ...    f   0   

## Part 2 - Exploring data, Testing hypotheses

The only thing we really know about this data is that A16 is the class label. Besides that, we have 6 continuous (float) features and 9 categorical features.

Explore the data: you can use whatever approach (tables, utility functions, visualizations) to get an impression of the distributions and relationships of the variables. In general, your goal is to understand how the features are different when grouped by the two class labels (`+` and `-`).

For the 6 continuous features, how are they different when split between the two class labels? Choose two features to run t-tests (again split by class label) - specifically, select one feature that is *extremely* different between the classes, and another feature that is notably less different (though perhaps still "statistically significantly" different). You may have to explore more than two features to do this.

For the categorical features, explore by creating "cross tabs" (aka [contingency tables](https://en.wikipedia.org/wiki/Contingency_table)) between them and the class label, and apply the Chi-squared test to them. [pandas.crosstab](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.crosstab.html) can create contingency tables, and [scipy.stats.chi2_contingency](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html) can calculate the Chi-squared statistic for them.

There are 9 categorical features - as with the t-test, try to find one where the Chi-squared test returns an extreme result (rejecting the null that the data are independent), and one where it is less extreme.

**NOTE** - "less extreme" just means smaller test statistic/larger p-value. Even the least extreme differences may be strongly statistically significant.

Your *main* goal is the hypothesis tests, so don't spend too much time on the exploration/visualization piece. That is just a means to an end - use simple visualizations, such as boxplots or a scatter matrix (both built in to pandas), to get a feel for the overall distribution of the variables.

This is challenging, so manage your time and aim for a baseline of at least running two t-tests and two Chi-squared tests before polishing. And don't forget to answer the questions in part 3, even if your results in this part aren't what you want them to be.

In [3]:
plus = df[df.A16 == '+']
print(plus.shape)
plus.head()

(307, 16)


A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  00202    0   +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g  00043  560   +
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  00280  824   +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  00100    3   +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  00120    0   +

In [4]:
minus = df[df.A16 == '-']
print(minus.shape)
minus.head()

(383, 16)


A1     A2   A3 A4 A5  A6  A7      A8 A9 A10  A11 A12 A13    A14  A15 A16
70  b  32.33  7.5  u  g   e  bb   1.585  t   f    0   t   s  00420    0   -
71  b  34.83  4.0  u  g   d  bb  12.500  t   f    0   t   g    NaN    0   -
72  a  38.58  5.0  u  g  cc   v  13.500  t   f    0   t   g  00980    0   -
73  b  44.25  0.5  u  g   m   v  10.750  t   f    0   f   s  00400    0   -
74  b  44.83  7.0  y  p   c   v   1.625  f   f    0   f   g  00160    2   -

In [5]:
from scipy import stats

stats.ttest_1samp(plus['A11'], .5, nan_policy='omit')

Ttest_1sampResult(statistic=11.382560629001722, pvalue=2.8798299332810433e-25)

In [6]:
stats.ttest_1samp(minus['A11'], .5, nan_policy='omit')

Ttest_1sampResult(statistic=1.3580856177707235, pvalue=0.17523808826084886)

In [7]:
table_observed = pd.crosstab(df['A16'], df['A11'])
table_observed.T

A16   +    -
A11         
0    98  297
1    35   36
2    19   26
3    20    8
4    12    3
5    16    2
6    20    3
7    15    1
8    10    0
9    10    0
10    4    4
11   18    1
12    7    1
13    1    0
14    8    0
15    4    0
16    3    0
17    2    0
19    1    0
20    1    1
23    1    0
40    1    0
67    1    0

In [8]:
table_observed_w_marg = pd.crosstab(df['A16'], df['A11'], margins=True)
table_observed_w_marg.head()

A11    0   1   2   3   4   5   6   7   8  ...  15  16  17  19  20  23  40  67  All
A16                                       ...                                     
+     98  35  19  20  12  16  20  15  10  ...   4   3   2   1   1   1   1   1  307
-    297  36  26   8   3   2   3   1   0  ...   0   0   0   0   1   0   0   0  383
All  395  71  45  28  15  18  23  16  10  ...   4   3   2   1   2   1   1   1  690

[3 rows x 24 columns]

In [9]:
table_observed_w_marg['All']

A16
+      307
-      383
All    690
Name: All, dtype: int64

In [10]:
table_observed_w_marg.T['All']

A11
0      395
1       71
2       45
3       28
4       15
5       18
6       23
7       16
8       10
9       10
10       8
11      19
12       8
13       1
14       8
15       4
16       3
17       2
19       1
20       2
23       1
40       1
67       1
All    690
Name: All, dtype: int64

In [11]:
table_observed_w_marg['All'].values[:-1]

array([307, 383])

In [12]:
np.outer(table_observed_w_marg['All'].values[:-1], table_observed_w_marg.T['All'].values[:-1])/table_observed_w_marg.T['All'].values[-1]

array([[175.74637681,  31.58985507,  20.02173913,  12.45797101,
          6.67391304,   8.00869565,  10.23333333,   7.11884058,
          4.44927536,   4.44927536,   3.55942029,   8.45362319,
          3.55942029,   0.44492754,   3.55942029,   1.77971014,
          1.33478261,   0.88985507,   0.44492754,   0.88985507,
          0.44492754,   0.44492754,   0.44492754],
       [219.25362319,  39.41014493,  24.97826087,  15.54202899,
          8.32608696,   9.99130435,  12.76666667,   8.88115942,
          5.55072464,   5.55072464,   4.44057971,  10.54637681,
          4.44057971,   0.55507246,   4.44057971,   2.22028986,
          1.66521739,   1.11014493,   0.55507246,   1.11014493,
          0.55507246,   0.55507246,   0.55507246]])

In [13]:
A16_totals = table_observed_w_marg['All'].values[:-1]
A16_totals

array([307, 383])

In [14]:
A11_totals = table_observed_w_marg.T['All'].values[:-1]
A11_totals

array([395,  71,  45,  28,  15,  18,  23,  16,  10,  10,   8,  19,   8,
         1,   8,   4,   3,   2,   1,   2,   1,   1,   1])

In [15]:
expected = np.outer(A16_totals, A11_totals)/A11_totals.sum()
expected

array([[175.74637681,  31.58985507,  20.02173913,  12.45797101,
          6.67391304,   8.00869565,  10.23333333,   7.11884058,
          4.44927536,   4.44927536,   3.55942029,   8.45362319,
          3.55942029,   0.44492754,   3.55942029,   1.77971014,
          1.33478261,   0.88985507,   0.44492754,   0.88985507,
          0.44492754,   0.44492754,   0.44492754],
       [219.25362319,  39.41014493,  24.97826087,  15.54202899,
          8.32608696,   9.99130435,  12.76666667,   8.88115942,
          5.55072464,   5.55072464,   4.44057971,  10.54637681,
          4.44057971,   0.55507246,   4.44057971,   2.22028986,
          1.66521739,   1.11014493,   0.55507246,   1.11014493,
          0.55507246,   0.55507246,   0.55507246]])

In [16]:
table_expected = pd.DataFrame(expected)
table_expected.columns = table_observed.columns
table_expected.index = table_observed.index
table_expected

A11          0          1          2   ...        23        40        67
A16                                    ...                              
+    175.746377  31.589855  20.021739  ...  0.444928  0.444928  0.444928
-    219.253623  39.410145  24.978261  ...  0.555072  0.555072  0.555072

[2 rows x 23 columns]

In [17]:
table_observed

A11   0   1   2   3   4   5   6   7   8   ...  14  15  16  17  19  20  23  40  67
A16                                       ...                                    
+     98  35  19  20  12  16  20  15  10  ...   8   4   3   2   1   1   1   1   1
-    297  36  26   8   3   2   3   1   0  ...   0   0   0   0   0   1   0   0   0

[2 rows x 23 columns]

In [18]:
deviation = table_observed - table_expected
deviation

A11         0         1         2   ...        23        40        67
A16                                 ...                              
+   -77.746377  3.410145 -1.021739  ...  0.555072  0.555072  0.555072
-    77.746377 -3.410145  1.021739  ... -0.555072 -0.555072 -0.555072

[2 rows x 23 columns]

In [19]:
deviation_sq = deviation**2
deviation_sq

A11           0          1         2   ...        23        40        67
A16                                    ...                              
+    6044.499107  11.629088  1.043951  ...  0.308105  0.308105  0.308105
-    6044.499107  11.629088  1.043951  ...  0.308105  0.308105  0.308105

[2 rows x 23 columns]

In [20]:
fraction = deviation_sq/table_expected
fraction

A11         0         1         2   ...        23        40        67
A16                                 ...                              
+    34.393307  0.368127  0.052141  ...  0.692485  0.692485  0.692485
-    27.568526  0.295079  0.041794  ...  0.555072  0.555072  0.555072

[2 rows x 23 columns]

In [21]:
fraction.values.sum()

203.41293121441763

In [22]:
table_observed

A11   0   1   2   3   4   5   6   7   8   ...  14  15  16  17  19  20  23  40  67
A16                                       ...                                    
+     98  35  19  20  12  16  20  15  10  ...   8   4   3   2   1   1   1   1   1
-    297  36  26   8   3   2   3   1   0  ...   0   0   0   0   0   1   0   0   0

[2 rows x 23 columns]

In [23]:
from scipy.stats import chi2_contingency

chi2, p, df, expect = chi2_contingency(table_observed)
print(f'chi2 stat: {chi2}')
print(f'p-value: {p}')
print(f'df: {df}')
print(f'expected freq: {expect}')

chi2 stat: 203.41293121441763
p-value: 2.4412392119596036e-31
df: 22
expected freq: [[175.74637681  31.58985507  20.02173913  12.45797101   6.67391304
    8.00869565  10.23333333   7.11884058   4.44927536   4.44927536
    3.55942029   8.45362319   3.55942029   0.44492754   3.55942029
    1.77971014   1.33478261   0.88985507   0.44492754   0.88985507
    0.44492754   0.44492754   0.44492754]
 [219.25362319  39.41014493  24.97826087  15.54202899   8.32608696
    9.99130435  12.76666667   8.88115942   5.55072464   5.55072464
    4.44057971  10.54637681   4.44057971   0.55507246   4.44057971
    2.22028986   1.66521739   1.11014493   0.55507246   1.11014493
    0.55507246   0.55507246   0.55507246]]


In [73]:
column_headers = ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16']
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data', header=None, names=column_headers)
df = df.replace({'?':np.NaN})
df.head()


A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  00202    0   +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g  00043  560   +
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  00280  824   +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  00100    3   +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  00120    0   +

In [74]:
table_observed = pd.crosstab(df['A16'], df['A8'])
table_observed.T

A16      +   -
A8            
0.000   18  52
0.040   13  20
0.085    5  21
0.125    5  25
0.165    2  20
0.210    2   4
0.250    7  28
0.290    3   9
0.335    1   4
0.375    3   4
0.415    2   6
0.455    0   1
0.460    1   0
0.500    5  23
0.540    1   5
0.585    1   5
0.625    2   0
0.665    2   4
0.710    1   0
0.750    6   6
0.790    0   1
0.795    0   1
0.835    3   2
0.875    2   3
0.960    1   1
1.000    9  22
1.040    1   0
1.085    4   2
1.165    0   4
1.210    2   0
...     ..  ..
7.415    1   0
7.500    2   1
7.585    1   0
7.875    1   0
7.960    1   0
8.000    2   0
8.290    0   1
8.500    4   1
8.625    1   0
8.665    1   0
9.000    1   0
9.460    0   1
10.000   3   2
10.750   0   1
11.000   2   0
11.500   0   1
12.500   1   1
12.750   2   0
13.000   1   0
13.500   0   1
13.875   1   1
14.000   3   0
14.415   1   0
15.000   3   0
15.500   1   0
16.000   1   0
17.500   1   0
18.000   1   0
20.000   2   0
28.500   1   0

[132 rows x 2 columns]

In [75]:
table_observed_w_marg = pd.crosstab(df['A16'], df['A8'], margins=True)
table_observed_w_marg.head()

A8   0.0  0.04  0.085  0.125  0.165  0.21  ...  16.0  17.5  18.0  20.0  28.5  All
A16                                        ...                                   
+     18    13      5      5      2     2  ...     1     1     1     2     1  307
-     52    20     21     25     20     4  ...     0     0     0     0     0  383
All   70    33     26     30     22     6  ...     1     1     1     2     1  690

[3 rows x 133 columns]

In [76]:
table_observed_w_marg['All']

A16
+      307
-      383
All    690
Name: All, dtype: int64

In [77]:
table_observed_w_marg.T['All']

A8
0.0        70
0.04       33
0.085      26
0.125      30
0.165      22
0.21        6
0.25       35
0.29       12
0.335       5
0.375       7
0.415       8
0.455       1
0.46        1
0.5        28
0.54        6
0.585       6
0.625       2
0.665       6
0.71        1
0.75       12
0.79        1
0.795       1
0.835       5
0.875       5
0.96        2
1.0        31
1.04        1
1.085       6
1.165       4
1.21        2
         ... 
7.5         3
7.585       1
7.875       1
7.96        1
8.0         2
8.29        1
8.5         5
8.625       1
8.665       1
9.0         1
9.46        1
10.0        5
10.75       1
11.0        2
11.5        1
12.5        2
12.75       2
13.0        1
13.5        1
13.875      2
14.0        3
14.415      1
15.0        3
15.5        1
16.0        1
17.5        1
18.0        1
20.0        2
28.5        1
All       690
Name: All, Length: 133, dtype: int64

In [78]:
table_observed_w_marg['All'].values[:-1]

array([307, 383])

In [79]:
np.outer(table_observed_w_marg['All'].values[:-1], table_observed_w_marg.T['All'].values[:-1])/table_observed_w_marg.T['All'].values[-1]

array([[31.14492754, 14.6826087 , 11.56811594, 13.34782609,  9.7884058 ,
         2.66956522, 15.57246377,  5.33913043,  2.22463768,  3.11449275,
         3.55942029,  0.44492754,  0.44492754, 12.45797101,  2.66956522,
         2.66956522,  0.88985507,  2.66956522,  0.44492754,  5.33913043,
         0.44492754,  0.44492754,  2.22463768,  2.22463768,  0.88985507,
        13.79275362,  0.44492754,  2.66956522,  1.77971014,  0.88985507,
         4.44927536,  1.33478261,  0.88985507,  0.88985507,  1.33478261,
         0.88985507, 11.12318841,  0.44492754,  2.22463768,  2.22463768,
         1.33478261,  0.44492754,  6.67391304,  0.88985507,  0.44492754,
         0.44492754,  7.11884058,  0.44492754,  0.88985507,  0.44492754,
         0.44492754,  4.44927536,  1.33478261,  0.44492754,  0.88985507,
         0.88985507,  0.44492754,  7.56376812,  0.44492754,  0.88985507,
         0.88985507,  0.44492754,  1.33478261,  0.44492754,  4.8942029 ,
         0.88985507,  1.33478261,  0.44492754,  0.8

In [80]:
A16_totals = table_observed_w_marg['All'].values[:-1]
A16_totals

array([307, 383])

In [81]:
A8_totals = table_observed_w_marg.T['All'].values[:-1]
A8_totals

array([70, 33, 26, 30, 22,  6, 35, 12,  5,  7,  8,  1,  1, 28,  6,  6,  2,
        6,  1, 12,  1,  1,  5,  5,  2, 31,  1,  6,  4,  2, 10,  3,  2,  2,
        3,  2, 25,  1,  5,  5,  3,  1, 15,  2,  1,  1, 16,  1,  2,  1,  1,
       10,  3,  1,  2,  2,  1, 17,  1,  2,  2,  1,  3,  1, 11,  2,  3,  1,
        2,  1,  3,  1, 12,  3,  1,  8,  1,  4,  1,  1,  6,  1,  1,  2, 13,
        1,  2,  1,  1,  2,  1,  1,  7,  1,  4,  3,  1,  1,  6,  1,  5,  1,
        1,  3,  1,  1,  1,  2,  1,  5,  1,  1,  1,  1,  5,  1,  2,  1,  2,
        2,  1,  1,  2,  3,  1,  3,  1,  1,  1,  1,  2,  1])

In [82]:
expected = np.outer(A16_totals, A8_totals)/A8_totals.sum()
expected

array([[31.14492754, 14.6826087 , 11.56811594, 13.34782609,  9.7884058 ,
         2.66956522, 15.57246377,  5.33913043,  2.22463768,  3.11449275,
         3.55942029,  0.44492754,  0.44492754, 12.45797101,  2.66956522,
         2.66956522,  0.88985507,  2.66956522,  0.44492754,  5.33913043,
         0.44492754,  0.44492754,  2.22463768,  2.22463768,  0.88985507,
        13.79275362,  0.44492754,  2.66956522,  1.77971014,  0.88985507,
         4.44927536,  1.33478261,  0.88985507,  0.88985507,  1.33478261,
         0.88985507, 11.12318841,  0.44492754,  2.22463768,  2.22463768,
         1.33478261,  0.44492754,  6.67391304,  0.88985507,  0.44492754,
         0.44492754,  7.11884058,  0.44492754,  0.88985507,  0.44492754,
         0.44492754,  4.44927536,  1.33478261,  0.44492754,  0.88985507,
         0.88985507,  0.44492754,  7.56376812,  0.44492754,  0.88985507,
         0.88985507,  0.44492754,  1.33478261,  0.44492754,  4.8942029 ,
         0.88985507,  1.33478261,  0.44492754,  0.8

In [83]:
table_expected = pd.DataFrame(expected)
table_expected.columns = table_observed.columns
table_expected.index = table_observed.index
table_expected

A8      0.000      0.040      0.085   ...    18.000    20.000    28.500
A16                                   ...                              
+    31.144928  14.682609  11.568116  ...  0.444928  0.889855  0.444928
-    38.855072  18.317391  14.431884  ...  0.555072  1.110145  0.555072

[2 rows x 132 columns]

In [84]:
table_observed

A8   0.000   0.040   0.085   0.125   ...  17.500  18.000  20.000  28.500
A16                                  ...                                
+        18      13       5       5  ...       1       1       2       1
-        52      20      21      25  ...       0       0       0       0

[2 rows x 132 columns]

In [85]:
deviation = table_observed - table_expected
deviation

A8      0.000     0.040     0.085   ...    18.000    20.000    28.500
A16                                 ...                              
+   -13.144928 -1.682609 -6.568116  ...  0.555072  1.110145  0.555072
-    13.144928  1.682609  6.568116  ... -0.555072 -1.110145 -0.555072

[2 rows x 132 columns]

In [86]:
deviation_sq = deviation**2
deviation_sq

A8      0.000     0.040      0.085   ...    18.000    20.000    28.500
A16                                  ...                              
+    172.78912  2.831172  43.140147  ...  0.308105  1.232422  0.308105
-    172.78912  2.831172  43.140147  ...  0.308105  1.232422  0.308105

[2 rows x 132 columns]

In [87]:
fraction = deviation_sq/table_expected
fraction


A8     0.000     0.040     0.085   ...    18.000    20.000    28.500
A16                                ...                              
+    5.547906  0.192825  3.729228  ...  0.692485  1.384969  0.692485
-    4.447016  0.154562  2.989225  ...  0.555072  1.110145  0.555072

[2 rows x 132 columns]

In [88]:
fraction.values.sum()

214.15309112989937

In [89]:
table_observed

A8   0.000   0.040   0.085   0.125   ...  17.500  18.000  20.000  28.500
A16                                  ...                                
+        18      13       5       5  ...       1       1       2       1
-        52      20      21      25  ...       0       0       0       0

[2 rows x 132 columns]

In [90]:
from scipy.stats import chi2_contingency

chi2, p, df, expect = chi2_contingency(table_observed)
print(f'chi2 stat: {chi2}')
print(f'p-value: {p}')
print(f'df: {df}')
print(f'expected freq: {expect}')

chi2 stat: 214.15309112989937
p-value: 6.169823802314779e-06
df: 131
expected freq: [[31.14492754 14.6826087  11.56811594 13.34782609  9.7884058   2.66956522
  15.57246377  5.33913043  2.22463768  3.11449275  3.55942029  0.44492754
   0.44492754 12.45797101  2.66956522  2.66956522  0.88985507  2.66956522
   0.44492754  5.33913043  0.44492754  0.44492754  2.22463768  2.22463768
   0.88985507 13.79275362  0.44492754  2.66956522  1.77971014  0.88985507
   4.44927536  1.33478261  0.88985507  0.88985507  1.33478261  0.88985507
  11.12318841  0.44492754  2.22463768  2.22463768  1.33478261  0.44492754
   6.67391304  0.88985507  0.44492754  0.44492754  7.11884058  0.44492754
   0.88985507  0.44492754  0.44492754  4.44927536  1.33478261  0.44492754
   0.88985507  0.88985507  0.44492754  7.56376812  0.44492754  0.88985507
   0.88985507  0.44492754  1.33478261  0.44492754  4.8942029   0.88985507
   1.33478261  0.44492754  0.88985507  0.44492754  1.33478261  0.44492754
   5.33913043  1.33478261  0

## Part 3 - Analysis and Interpretation

Now that you've looked at the data, answer the following questions:

- Interpret and explain the two t-tests you ran - what do they tell you about the relationships between the continuous features you selected and the class labels?

- Interpret and explain the two Chi-squared tests you ran - what do they tell you about the relationships between the categorical features you selected and the class labels?

- What was the most challenging part of this sprint challenge?

Answer with text, but feel free to intersperse example code/results or refer to it from earlier.

*Your words here!*

- Column A11 for "+" had a lot more variance than "-"

- Since the P-value is much lower than the critical value for chi2 with 22 degrees of variance, we can ecpet this value as true. I got a siimlar P-value for the second Chi2 test even though I used columns with much more extreme variance. With the second test, I can still saftly say that the value given is true.

- wrapping my mind around Chi2 